/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/room": {
    get: operations["getRoomList"];
    post: operations["createRoom"];
  };
  "/room/{roomId}": {
    delete: operations["RemoveRoom"];
  };
}

export interface components {
  schemas: {
    ApiResponse: {
      /** Format: int32 */
      code?: number;
      type?: string;
      message?: string;
      errorCode?: components["schemas"]["ErrorCode"];
    };
    /** @enum {string} */
    ErrorCode:
      | "MISSING_PARAMETER"
      | "MISSING_TOKEN"
      | "INVALID_TOKEN"
      | "ACTION_NOT_ALLOWED"
      | "NOT_FOUND"
      | "SERVER_ERROR"
      | "UNEXPECTED_ERROR";
    RoomReq: {
      name: string;
    };
    RoomRes: {
      id?: string;
      name?: string;
      createdTime?: string;
    };
  };
  responses: {
    /** Bad request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["ApiResponse"];
      };
    };
    /** Unauthorized */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["ApiResponse"];
      };
    };
    /** Forbidden */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["ApiResponse"];
      };
    };
    /** Not Found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["ApiResponse"];
      };
    };
  };
}

export interface operations {
  getRoomList: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["RoomRes"][];
        };
      };
      /** No Content */
      204: never;
      400: components["responses"]["BadRequest"];
    };
  };
  createRoom: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["RoomRes"];
        };
      };
      /** No Content */
      204: never;
      400: components["responses"]["BadRequest"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoomReq"];
      };
    };
  };
  RemoveRoom: {
    parameters: {
      path: {
        roomId: string;
      };
    };
    responses: {
      /** Deleted */
      204: never;
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
    };
  };
}

export interface external {}
